cc_library(
    name = "CGI",
    srcs = ["kCGI.cpp"],
    hdrs = ["fastcgi.h","kCGI.h"],
    visibility = ["//visibility:public"],
    copts = ["-Isrc/logger"],
    deps = [
            "//src/logger:logger",
            ]
)


