cc_library(
    name = "CJsonObject",
    srcs = [
        "cJSON.cpp",
        "gason.cpp",
        "CJsonObject.cpp",
        ],
    hdrs = [
        "cJSON.h",
        "gason.h",
        "CJsonObject.hpp"
        ],
    visibility = ["//visibility:public"],
)


