cc_library(
    name = "net_tool",
    srcs = ["net_tool.cpp"],
    hdrs = ["net_tool.h"],
    visibility = ["//visibility:public"],
    copts = ["-Isrc/logger"],
    deps = [
            "//src/logger:logger",
            ]
)


