cc_library(
    name = "BmpTool",
    srcs = ["BmpTool.cpp","bmpfile.c"],
    hdrs = ["BmpTool.h","bmpfile.h"],
    visibility = ["//visibility:public"],
    copts = ["-Isrc/logger"],
    deps = [
            "//src/logger:logger",
            ]
)


