cc_library(
    name = "BmpTool",
    srcs = ["BmpTool.cpp"],
    hdrs = ["BmpTool.h"],
    visibility = ["//visibility:public"],
    copts = ["-Isrc/logger"],
    deps = [
            "//src/logger:logger",
            ]
)


