cc_library(
    name = "socket",
    srcs = [
        "socket.cpp"
        ],
    hdrs = [
        "socket.h"
        ],
    visibility = ["//visibility:public"],
    copts = ["-Isrc/logger","-Isrc/socket"],
    deps = [
            "//src/logger:logger",
            ]
)


