cc_library(
    name = "thread_pool",
    srcs = [
        "thread_pool.cpp"
        ],
    hdrs = [
        "thread_pool.h"
        ],
    visibility = ["//visibility:public"],
    copts = ["-Isrc/logger","-Isrc/thread_pool"],
    deps = [
            "//src/logger:logger",
            ]
)


