name: bazel-build CI

on:
  push:
    branches: [] # [ master,dev ]
  pull_request:
    branches: [] # [ master,dev ]

jobs:

  ubuntu-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: run
        uses: ngalaiko/bazel-action/1.2.1@master
        with:
          args: build //...