name: C/C++ CI

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build-ubuntu && cd build-ubuntu && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build-ubuntu
      - uses: actions/upload-artifact@v2
      with:
        name: libtools-ubuntu
        path: |
          build-ubuntu/libTools.a


  win-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build-windows && cd build-windows && cmake ..
      - name: build
        run: cmake --build build-windows
      - uses: actions/upload-artifact@v2
      with:
        name: libtools-windows
        path: |
          build-windows/libTools.a

  macOS-build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build-macOS && cd build-macOS && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build-macOS
      - uses: actions/upload-artifact@v2
      with:
        name: libtools-macOS
        path: |
          build-macOS/libTools.a

  bazel-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: run
        uses: ngalaiko/bazel-action/1.2.1@master
        with:
          args: build //...